Frontends/FreeCourse.Web/Models/UserViewModel.cs
namespace FreeCourse.Web.Models
{
    public class UserViewModel
    {
        public string Id { get; set; }

        public string UserName { get; set; }

        public string Email { get; set; }

        public string City { get; set; }

        public IEnumerable<string> GetUserProps()
        {
            yield return UserName;
            yield return Email;
            yield return City;
        }
    }
}

Frontends/FreeCourse.Web/Controllers/CoursesController.cs
using FreeCourse.Shared.Services;
using FreeCourse.Web.Models.Catalog;
using FreeCourse.Web.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FreeCourse.Web.Controllers
{
    [Authorize]
    public class CoursesController : Controller
    {
        private readonly ICatalogService _catalogService;
        private readonly ISharedIdentityService _sharedIdentityService;

        public CoursesController(ICatalogService catalogService, ISharedIdentityService sharedIdentityService)
        {
            _catalogService = catalogService;
            _sharedIdentityService = sharedIdentityService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _catalogService.GetAllCourseByUserIdAsync(_sharedIdentityService.GetUserId));
        }

        public async Task<IActionResult> Create()
        {
            var categories = await _catalogService.GetAllCategoryAsync();

            ViewBag.categoryList = new SelectList(categories, "Id", "Name");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CourseCreateInput courseCreateInput)
        {
            var categories = await _catalogService.GetAllCategoryAsync();

            ViewBag.categoryList = new SelectList(categories, "Id", "Name");

            if (!ModelState.IsValid)
            {
                return View();
            }

            courseCreateInput.UserId = _sharedIdentityService.GetUserId;

            await _catalogService.CreateCourseAsync(courseCreateInput);

            return RedirectToAction(nameof(Index));
        }
    }
}

Frontends/FreeCourse.Web/Controllers/UserController.cs
using FreeCourse.Web.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FreeCourse.Web.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _userService.GetUser());
        }
    }
}

Frontends/FreeCourse.Web/Views/User/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

@model UserViewModel

<div class="row">
    <div class="col-md-9">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Kullanıcı Bilgileri</h5>

                <table class="table table-striped">
                    <tr>
                        <td>Kullanıcı Adı</td>
                        <td>@Model.UserName</td>
                    </tr>
                    <tr>
                        <td>E-Mail</td>
                        <td>@Model.Email</td>
                    </tr>
                    <tr>
                        <td>Şehir</td>
                        <td>@Model.City</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="list-group">
            <a asp-controller="Courses" asp-action="Index" class="list-group-item list-group-item-action">Kurslarım</a>
        </div>
    </div>
</div>